version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: content_factory_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ai_content_factory
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - content_factory_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: content_factory_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - content_factory_network

  # Backend API
  backend:
    build:
      context: ./ai-content-factory
      dockerfile: Dockerfile
    container_name: content_factory_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/ai_content_factory?authSource=admin
      REDIS_URL: redis://redis:6379
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./ai-content-factory/.env
    networks:
      - content_factory_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: content_factory_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - content_factory_network

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: content_factory_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (if using HTTPS)
    depends_on:
      - frontend
      - backend
    networks:
      - content_factory_network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  content_factory_network:
    driver: bridge